### ISSUE TITLE
What is the need for the `eventsourcing_sequence` table?

### ISSUE THREAD

**Issue by vab2048** [JohT/showcase-quarkus-eventsourcing#81]
@JohT Thanks for the repo :) I am using it for inspiration for my own exploration into the Axon framework [here](https://github.com/vab2048/axon-exhibition).

A question: in the [SQL schema](https://github.com/JohT/showcase-quarkus-eventsourcing/blob/master/showcase-quarkus-eventsourcing/src/main/resources/db/command/common/V1.0.0__AxonOnMicroprofileTryoutEventsourcing.sql) there are the lines:

```sql
CREATE TABLE "axon_on_microprofile_tryout"."eventsourcing_sequence" (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME));

INSERT INTO "axon_on_microprofile_tryout"."eventsourcing_sequence"(SEQ_NAME, SEQ_COUNT) values ('ASSOCIATIONVALUEENTRY_ID', 0);
INSERT INTO "axon_on_microprofile_tryout"."eventsourcing_sequence"(SEQ_NAME, SEQ_COUNT) values ('DOMAINEVENTENTRY_GLOBAL_INDEX', 0);
```

I'm not sure I understand what exactly this is used for? Could you please explain?

**Comment by JohT** [comment]
I assume that this sequence table comes from JPA as a cause of `@GeneratedValue` inside AxonFramework JPA Entities. I once used Axon's JPA integration and configured it so that it generated the schema for me as a file. 

I later switched to JDBC and used the generated SQL schema to get started. I've found AxonFramework/cdi/issues/9](https://github.com/AxonFramework/cdi/issues/9#issuecomment-416087357) where the sequence shows up in a log too.

I'll try what happens when I drop the `eventsourcing_sequence` and let you know.

**Comment by JohT** [comment]
I've created the new database [schema version v3.0.0](https://github.com/JohT/showcase-quarkus-eventsourcing/blob/master/showcase-quarkus-eventsourcing/src/main/resources/db/command/common/V3.0.0__DropUnnecessarySequenceTable.sql) and dropped the sequence table there. It wasn't used and everything works fine without it. I've also added some comments in [V1.0.0__AxonOnMicroprofileTryoutEventsourcing.sql](https://github.com/JohT/showcase-quarkus-eventsourcing/blob/master/showcase-quarkus-eventsourcing/src/main/resources/db/command/common/V1.0.0__AxonOnMicroprofileTryoutEventsourcing.sql) for future reference.

Thank you for your hint. 👍

I'll close this issue, but don't hesitate to add further comments.
